[package]
name = "assembler_project"
version = "0.1.0"
authors = ["Derek Drost <rlwarrior32@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.1.0"